version: '3.9'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - '8000:8000'
        volumes:
            - .:/usr/app
        command: bash -c "npm run typeorm:run-migrations && npm run dev"
    db:
        image: postgres:12
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - data:/var/lib/postgresql/data

    pg-admin:
        image: dpage/pgadmin4:6
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@email.com
            - PGADMIN_DEFAULT_PASSWORD=admin
            - PGADMIN_LISTEN_PORT=5050
        ports:
            - '5050:5050'
        volumes:
            - pgadmin-data:/var/lib/postgresql/data

volumes:
    data:
    pgadmin-data:
